// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLtopgWePFQCgdZoYBAth6_BtXbG8YXO8',
    appId: '1:505047856229:web:df7ce3fe2a627b11f6428c',
    messagingSenderId: '505047856229',
    projectId: 'quickshop-ecommerce-5af15',
    authDomain: 'quickshop-ecommerce-5af15.firebaseapp.com',
    storageBucket: 'quickshop-ecommerce-5af15.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHoSJr-xxg7mpu_-dWSysorAYtv9G1mxo',
    appId: '1:505047856229:android:eea1294953800fdaf6428c',
    messagingSenderId: '505047856229',
    projectId: 'quickshop-ecommerce-5af15',
    storageBucket: 'quickshop-ecommerce-5af15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTEVCkP3CKBeCdasIdNke9WH7_ncV5CcY',
    appId: '1:505047856229:ios:925007ddfa8f8d5ff6428c',
    messagingSenderId: '505047856229',
    projectId: 'quickshop-ecommerce-5af15',
    storageBucket: 'quickshop-ecommerce-5af15.firebasestorage.app',
    androidClientId: '505047856229-fojnd020ko3806scq1phesmt1teccobv.apps.googleusercontent.com',
    iosClientId: '505047856229-1vd446a9p4o9ko8outhjc2iddlcin2sh.apps.googleusercontent.com',
    iosBundleId: 'ca.binfotech.quickShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTEVCkP3CKBeCdasIdNke9WH7_ncV5CcY',
    appId: '1:505047856229:ios:925007ddfa8f8d5ff6428c',
    messagingSenderId: '505047856229',
    projectId: 'quickshop-ecommerce-5af15',
    storageBucket: 'quickshop-ecommerce-5af15.firebasestorage.app',
    androidClientId: '505047856229-fojnd020ko3806scq1phesmt1teccobv.apps.googleusercontent.com',
    iosClientId: '505047856229-1vd446a9p4o9ko8outhjc2iddlcin2sh.apps.googleusercontent.com',
    iosBundleId: 'ca.binfotech.quickShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLtopgWePFQCgdZoYBAth6_BtXbG8YXO8',
    appId: '1:505047856229:web:2acd42dd2afd49cbf6428c',
    messagingSenderId: '505047856229',
    projectId: 'quickshop-ecommerce-5af15',
    authDomain: 'quickshop-ecommerce-5af15.firebaseapp.com',
    storageBucket: 'quickshop-ecommerce-5af15.firebasestorage.app',
  );

}